name: Build and Deploy

on:
push: 
branches:
- main
jobs: gh-pages
build-and-deploy:
runs-on: ubuntu-latest
steps:
- name: Chekout
uses: actions/checkout@v1
- uses: actions/setup-node@v1
whith:
path: ~/.npm
key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
restory-keys: |
${{ runner.os }}-node.
- name: Build
run: |
npm install 
npm run-script deploy
- name: Deploy
uses: JamesIves/github-pages-deploy-action@releases/v3
with: 
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
BRANCH: gh-pages
FOLDER: dist/workshop